<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="hunter_drone">

    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.05"/>
    <xacro:property name="rotor_radius" value="0.1"/>
    <xacro:property name="rotor_height" value="0.02"/>

    <material name="orange">
        <color rgba="1.0 0.5 0.0 1.0"/>
    </material>
    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_width} ${base_width} ${base_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_width} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
    </link>

    <xacro:macro name="rotor" params="prefix x y">
        <link name="${prefix}_rotor">
            <visual>
                <geometry>
                    <cylinder radius="${rotor_radius}" length="${rotor_height}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${rotor_radius}" length="${rotor_height}"/>
                </geometry>
            </collision>
        </link>

        <joint name="${prefix}_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_rotor"/>
            <origin xyz="${x} ${y} ${base_height/2 + rotor_height/2}" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
        </joint>
    </xacro:macro>

    <xacro:rotor prefix="front_left" x="${base_width/2}" y="${base_width/2}"/>
    <xacro:rotor prefix="front_right" x="${base_width/2}" y="-${base_width/2}"/>
    <xacro:rotor prefix="rear_left" x="-${base_width/2}" y="${base_width/2}"/>
    <xacro:rotor prefix="rear_right" x="-${base_width/2}" y="-${base_width/2}"/>

</robot>
